# Generated by Django 4.2.7 on 2024-05-08 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_post_likes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'default_related_name': 'comments', 'ordering': ['created']},
        ),
        migrations.RemoveIndex(
            model_name='post',
            name='base_post_date_po_88634f_idx',
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['-date_posted', 'slug'], name='base_post_date_po_5bc194_idx'),
        ),
    ]
