# Generated by Django 4.2.7 on 2024-05-20 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_comment_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'default_related_name': 'posts', 'ordering': ['-date_posted']},
        ),
    ]
